# Generated by Django 4.2.11 on 2024-04-03 06:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instructor", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instructor",
            name="money_earned",
            field=models.FloatField(default=0.0),
        ),
    ]
