# Generated by Django 4.2.11 on 2024-03-23 18:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_alter_user_contact_number_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="contact_number",
            field=models.CharField(
                max_length=13,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="userpermission",
            name="account",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="permission",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
