# Generated by Django 4.2.11 on 2024-03-21 06:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="rating",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="course",
            name="student_count",
            field=models.IntegerField(default=0),
        ),
    ]
