# Generated by Django 4.2.11 on 2024-04-03 06:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.FloatField(
                choices=[
                    ("1.0", "One"),
                    ("1.5", "Onehalf"),
                    ("2.0", "Two"),
                    ("2.5", "Twohalf"),
                    ("3.0", "Three"),
                    ("3.5", "Threehalf"),
                    ("4.0", "Four"),
                    ("4.5", "Fourhalf"),
                    ("5.0", "Five"),
                ],
                default=None,
            ),
        ),
    ]
