# Generated by Django 4.2.11 on 2024-03-20 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tutor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qualification", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("course_count", models.PositiveIntegerField(default=0)),
                ("money_earned", models.PositiveBigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("application_accepted", models.BooleanField(default=False)),
                (
                    "application_status",
                    models.CharField(
                        choices=[
                            ("accepted", "accepted"),
                            ("pending", "pending"),
                            ("rejected", "rejected"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("reason_for_rejection", models.TextField(blank=True, null=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tutor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "application_accepted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
